In [23]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [24]:
import pandas as pd
import numpy as np

# Importa as funções para os cálculos estatísticos. Ex: et.calc_iqr(df, 'coluna') - Faz o cálculo do IQR da coluna enviada
import estatistica as et

In [25]:
dados = 'csv/base/reservas.csv'
df = pd.read_csv(dados, sep=',')
df.head()

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
0,1,203,Q026,3,2024-10-28,2024-10-29,Site Próprio,2344.25,Confirmada,2024-10-21
1,2,30,Q033,3,2024-06-03,2024-06-07,Site Próprio,469.17,Confirmada,2024-05-07
2,3,47,Q004,1,2024-07-18,2024-07-25,Site Próprio,2358.47,Confirmada,2024-07-10
3,4,322,Q023,2,2024-08-19,2024-08-20,Telefone,1743.13,Confirmada,2024-08-15
4,5,286,Q013,2,2023-05-17,2023-05-22,Agência de Viagem,617.85,Confirmada,2023-05-09

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      1000 non-null   int64
 1   id_hospede      1000 non-null   int64
 2   id_quarto       1000 non-null   str
 3   id_hotel        1000 non-null   int64
 4   data_checkin    1000 non-null   str
 5   data_checkout   1000 non-null   str
 6   canal_reserva   995 non-null    str
 7   valor_diaria    997 non-null    float64
 8   status_reserva  1000 non-null   str
 9   data_reserva    1000 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 78.3 KB

In [27]:
df['status_reserva'].value_counts()

status_reserva
Confirmada     965
Overbooking     18
Cancelado        7
No-show          4
no-show          2
CONFIRMADA       2
confirmada       1
Cancelada        1
Name: count, dtype: int64

In [28]:
# Padroniza todos os valores de status_reserva para caixa alta e troca o valor CANCELADA para CANCELADO
df['status_reserva'] = df['status_reserva'].str.upper().replace('CANCELADA', 'CANCELADO')
df['status_reserva'].value_counts()

status_reserva
CONFIRMADA     968
OVERBOOKING     18
CANCELADO        8
NO-SHOW          6
Name: count, dtype: int64

In [29]:
# Remove a letra 'Q' do id_quarto e converte para inteiro
df['id_quarto'] = df['id_quarto'].str.replace('Q', '').astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      1000 non-null   int64
 1   id_hospede      1000 non-null   int64
 2   id_quarto       1000 non-null   int64
 3   id_hotel        1000 non-null   int64
 4   data_checkin    1000 non-null   str
 5   data_checkout   1000 non-null   str
 6   canal_reserva   995 non-null    str
 7   valor_diaria    997 non-null    float64
 8   status_reserva  1000 non-null   str
 9   data_reserva    1000 non-null   str
dtypes: float64(1), int64(4), str(5)
memory usage: 78.3 KB

In [30]:
# canal_reserva contém valores nulos
# Preenche as informações nulas com o valor 'Não informado'
df['canal_reserva'] = df['canal_reserva'].fillna('Não informado')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      1000 non-null   int64
 1   id_hospede      1000 non-null   int64
 2   id_quarto       1000 non-null   int64
 3   id_hotel        1000 non-null   int64
 4   data_checkin    1000 non-null   str
 5   data_checkout   1000 non-null   str
 6   canal_reserva   1000 non-null   str
 7   valor_diaria    997 non-null    float64
 8   status_reserva  1000 non-null   str
 9   data_reserva    1000 non-null   str
dtypes: float64(1), int64(4), str(5)
memory usage: 78.3 KB

In [31]:
# Cria um dicionário para mapeamento dos canais de reserva e faz um replace utilizando esse mapeamento
mapeamento_canais = {
    'EXPEDIA': 'Expedia',
    'booking.com': 'Booking.com',
    'site próprio': 'Site Próprio',
    'Agencia de Viagem': 'Agência de Viagem'
}
df['canal_reserva'] = df['canal_reserva'].replace(mapeamento_canais)
df['canal_reserva'].value_counts()

canal_reserva
Expedia              225
Booking.com          207
Site Próprio         206
Telefone             179
Agência de Viagem    178
Não informado          5
Name: count, dtype: int64

In [32]:
# Converte o tipo de data_checkin, data_checkout e data_reserva de string para datetime
df['data_checkin'] = pd.to_datetime(df['data_checkin'])
df['data_checkout'] = pd.to_datetime(df['data_checkout'])
df['data_reserva'] = pd.to_datetime(df['data_reserva'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      1000 non-null   int64
 1   id_hospede      1000 non-null   int64
 2   id_quarto       1000 non-null   int64
 3   id_hotel        1000 non-null   int64
 4   data_checkin    1000 non-null   datetime64[us]
 5   data_checkout   1000 non-null   datetime64[us]
 6   canal_reserva   1000 non-null   str
 7   valor_diaria    997 non-null    float64
 8   status_reserva  1000 non-null   str
 9   data_reserva    1000 non-null   datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 78.3 KB

In [33]:
# Mantém apenas as linhas onde a data de checkout é maior ou igual à data de checkin
df = df[df['data_checkout'] >= df['data_checkin']]
df = df[df['data_reserva'] <= df['data_checkin']]
df.info()

<class 'pandas.DataFrame'>
Index: 991 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      991 non-null    int64
 1   id_hospede      991 non-null    int64
 2   id_quarto       991 non-null    int64
 3   id_hotel        991 non-null    int64
 4   data_checkin    991 non-null    datetime64[us]
 5   data_checkout   991 non-null    datetime64[us]
 6   canal_reserva   991 non-null    str
 7   valor_diaria    988 non-null    float64
 8   status_reserva  991 non-null    str
 9   data_reserva    991 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 85.2 KB

In [34]:
df['valor_diaria'] = df['valor_diaria'].replace(0, np.nan)
df.info()

<class 'pandas.DataFrame'>
Index: 991 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      991 non-null    int64
 1   id_hospede      991 non-null    int64
 2   id_quarto       991 non-null    int64
 3   id_hotel        991 non-null    int64
 4   data_checkin    991 non-null    datetime64[us]
 5   data_checkout   991 non-null    datetime64[us]
 6   canal_reserva   991 non-null    str
 7   valor_diaria    987 non-null    float64
 8   status_reserva  991 non-null    str
 9   data_reserva    991 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 85.2 KB

In [35]:
# Mantém apenas as linhas onde o valor da diária é positivo e não nulo
df = df[(df['valor_diaria'] >= 0)]
df.info()

<class 'pandas.DataFrame'>
Index: 984 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      984 non-null    int64
 1   id_hospede      984 non-null    int64
 2   id_quarto       984 non-null    int64
 3   id_hotel        984 non-null    int64
 4   data_checkin    984 non-null    datetime64[us]
 5   data_checkout   984 non-null    datetime64[us]
 6   canal_reserva   984 non-null    str
 7   valor_diaria    984 non-null    float64
 8   status_reserva  984 non-null    str
 9   data_reserva    984 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 84.6 KB

In [36]:
# Elimina os id_hospede inexistentes
df = df[df['id_hospede'] <= 400]
df.info()

<class 'pandas.DataFrame'>
Index: 979 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      979 non-null    int64
 1   id_hospede      979 non-null    int64
 2   id_quarto       979 non-null    int64
 3   id_hotel        979 non-null    int64
 4   data_checkin    979 non-null    datetime64[us]
 5   data_checkout   979 non-null    datetime64[us]
 6   canal_reserva   979 non-null    str
 7   valor_diaria    979 non-null    float64
 8   status_reserva  979 non-null    str
 9   data_reserva    979 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 84.1 KB

In [37]:
# Faz o cálculo dos limites superior e inferior e filtra os outliers
limites_valor_diaria = et.calc_limites(df, 'valor_diaria')
out_sup_valor_diaria = df.loc[df['valor_diaria'] > limites_valor_diaria[1]]

print(f'Limite inferior: {et.calc_limites(df, 'valor_diaria')[0]}')
print(f'Limite superior: {et.calc_limites(df, 'valor_diaria')[1]}')

Limite inferior: -961.2074999999995
Limite superior: 4001.5724999999993

In [38]:
out_sup_valor_diaria

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
33,34,144,1,1,2024-04-28,2024-05-03,Booking.com,23785.17,CONFIRMADA,2024-04-05
177,178,130,57,5,2023-06-12,2023-06-18,Telefone,19486.09,CONFIRMADA,2023-04-20
320,321,213,39,4,2023-06-16,2023-06-17,Expedia,19122.22,CONFIRMADA,2023-05-06
511,512,57,25,3,2023-05-04,2023-05-12,Booking.com,24637.28,CONFIRMADA,2023-05-03
688,689,354,43,4,2024-10-08,2024-10-10,Não informado,16283.31,CONFIRMADA,2024-08-20

In [39]:
dados2 = 'csv/base/reservas_2025.csv'
df_2025 = pd.read_csv(dados2, sep=',')
df_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      500 non-null    int64
 1   id_hospede      500 non-null    int64
 2   id_quarto       500 non-null    str
 3   id_hotel        500 non-null    int64
 4   data_checkin    500 non-null    str
 5   data_checkout   500 non-null    str
 6   canal_reserva   500 non-null    str
 7   valor_diaria    497 non-null    float64
 8   status_reserva  500 non-null    str
 9   data_reserva    500 non-null    str
dtypes: float64(1), int64(3), str(6)
memory usage: 39.2 KB

In [40]:
# Padronização do novo DataFrame para evitar erros na concatenação
df_2025['data_checkin'] = pd.to_datetime(df_2025['data_checkin'])
df_2025['data_checkout'] = pd.to_datetime(df_2025['data_checkout'])
df_2025['data_reserva'] = pd.to_datetime(df_2025['data_reserva'])
df_2025 = df_2025[(df_2025['valor_diaria'] >= 0)]
df_2025['id_quarto'] = df_2025['id_quarto'].str.replace('Q', '').astype(int)
df_2025.info()

<class 'pandas.DataFrame'>
Index: 497 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      497 non-null    int64
 1   id_hospede      497 non-null    int64
 2   id_quarto       497 non-null    int64
 3   id_hotel        497 non-null    int64
 4   data_checkin    497 non-null    datetime64[us]
 5   data_checkout   497 non-null    datetime64[us]
 6   canal_reserva   497 non-null    str
 7   valor_diaria    497 non-null    float64
 8   status_reserva  497 non-null    str
 9   data_reserva    497 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 42.7 KB

In [41]:
# Concatenação dos dois DataFrames
df_reservas = pd.concat([df, df_2025], ignore_index=True)
df_reservas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1476 entries, 0 to 1475
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      1476 non-null   int64
 1   id_hospede      1476 non-null   int64
 2   id_quarto       1476 non-null   int64
 3   id_hotel        1476 non-null   int64
 4   data_checkin    1476 non-null   datetime64[us]
 5   data_checkout   1476 non-null   datetime64[us]
 6   canal_reserva   1476 non-null   str
 7   valor_diaria    1476 non-null   float64
 8   status_reserva  1476 non-null   str
 9   data_reserva    1476 non-null   datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 115.4 KB

In [42]:
# Exportação do DataFrame concatenado
df_reservas.to_csv('./csv/tratado/reservas_tratado.csv')