In [2]:
import pandas as pd
import numpy as np

In [3]:
dados = 'hoteis.csv'
df = pd.read_csv(dados, sep=',')
df

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas      120.0
1         2          Nara Recife          Recife     PE  4 estrelas       95.0
2         3        Nara Salvador        Salvador     BA  4 estrelas        NaN
3         4  Nara Rio de Janeiro  Rio De Janeiro     RJ  3 estrelas       80.0
4         5       Nara São Paulo       Sao Paulo     SP  6 estrelas      150.0

In [5]:
# Nara Salvador não tem número de quartos preenchido, deve ser decidido se será melhor excluir o dado
# quartos.csv, fazer somatorio do numero de quartos de Nara Salvador
# Muda a categoria 6 estrelas para 5 estrelas
df['categoria'] = df['categoria'].str.replace('6 estrelas', '5 estrelas')
df

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas      120.0
1         2          Nara Recife          Recife     PE  4 estrelas       95.0
2         3        Nara Salvador        Salvador     BA  4 estrelas        NaN
3         4  Nara Rio de Janeiro  Rio De Janeiro     RJ  3 estrelas       80.0
4         5       Nara São Paulo       Sao Paulo     SP  5 estrelas      150.0

In [6]:
# Preenche o número de quartos do Nara Salvador com o somatório do número de quartos da base quartos.csv
df['n_quartos'] = df['n_quartos'].fillna(11)
df

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas      120.0
1         2          Nara Recife          Recife     PE  4 estrelas       95.0
2         3        Nara Salvador        Salvador     BA  4 estrelas       11.0
3         4  Nara Rio de Janeiro  Rio De Janeiro     RJ  3 estrelas       80.0
4         5       Nara São Paulo       Sao Paulo     SP  5 estrelas      150.0

In [8]:
# Corrige erros de digitação na coluna cidade
df['cidade'] = df['cidade'].str.replace('Rio De Janeiro', 'Rio de Janeiro').replace('Sao Paulo', 'São Paulo')
df

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas      120.0
1         2          Nara Recife          Recife     PE  4 estrelas       95.0
2         3        Nara Salvador        Salvador     BA  4 estrelas       11.0
3         4  Nara Rio de Janeiro  Rio de Janeiro     RJ  3 estrelas       80.0
4         5       Nara São Paulo       São Paulo     SP  5 estrelas      150.0